### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by lguychard**
- Update `sourcegraph` package to v23.0.1
- Inject sourcegraph API in utility functions rather than directly referencing it, and mock it in tests using `@sourcegraph/extension-api-stubs`
- Remove irrelevant `resolveURI()`, `codecovParamsForRepo()` tests.

Unit tests now pass.

### CODE REVIEW

**Comment by 3askaal** [comment]
Looks good man! These tests are way more clear then before. Not sure if passing the whole sourcegraph lib to each function you need to test is the most convenient way. But going to approve this.

You branched off of my branch right? I think so because this PR passed the Travis pipeline..

**Comment by lguychard** [comment]
@3askaal TBH I think we could probably refactor `codecovParamsForRepositoryCommit()` to not take `sourcegraph` as an argument, and simply inject `Settings` or an `Endpoint`. I'll probably address that in a follow-up PR.

**Comment by felixfbecker** [comment]
I would also prefer to only call the Sourcegraph API at the top level and pass settings down

**Review by DboyRedd — COMMENTED** [review]
How do you pull it

**Pull request merged**
